name: "Chromatic"

# Event for the workflow
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
on: push

permissions:
  contents: read
  packages: read

jobs:
  chromatic-deployment:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to retrieve git history

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm clean-install

      - name: publish to chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
          onlyChanged: false # 👈 Disable TurboSnap, see MOSAIQ-3198
        id: chromatic-publish
